"""listings and photos

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.Enum('room', '1bhk', '2bhk', '3bhk', 'flat', name='listing_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'rented', 'expired', 'removed', name='listing_status'), server_default='draft', nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('water_charge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('waste_charge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('internet_charge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parking_charge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('agent_commission', sa.Integer(), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False),
    sa.Column('furnishing', sa.Enum('unfurnished', 'semi', 'full', name='furnishing'), server_default='unfurnished', nullable=False),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.Column('max_occupants', sa.SmallInteger(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('landmark', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('public_lat', sa.Float(), nullable=False),
    sa.Column('public_lng', sa.Float(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deposit >= 0 AND water_charge >= 0 AND waste_charge >= 0 AND internet_charge >= 0 AND parking_charge >= 0', name=op.f('ck_listings_charges_non_negative')),
    sa.CheckConstraint('rent > 0', name=op.f('ck_listings_rent_positive')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_listings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index('ix_listings_amenities', 'listings', ['amenities'], unique=False, postgresql_using='gin')
    op.create_index('ix_listings_location', 'listings', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_index('ix_listings_status_confirmed', 'listings', ['status', 'last_confirmed_at'], unique=False)
    op.create_table('listing_photos',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', name='photo_status'), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_photos_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_photos')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_listing_photos_storage_key'))
    )
    op.create_index(op.f('ix_listing_photos_listing_id'), 'listing_photos', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_photos_listing_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    op.drop_index('ix_listings_status_confirmed', table_name='listings')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index('ix_listings_location', table_name='listings', postgresql_using='gist')
    op.drop_index('ix_listings_amenities', table_name='listings', postgresql_using='gin')
    op.drop_table('listings')
    # Autogenerate forgets these: drop the enum types too, or re-running upgrade fails.
    for enum_name in ('photo_status', 'furnishing', 'listing_status', 'listing_type'):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
