"""reports and moderation

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 10:05:02.977273
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_admin_actions_admin_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions'))
    )
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_target_id'), 'admin_actions', ['target_id'], unique=False)
    op.create_table('listing_reports',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_reports_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_listing_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_listing_reports_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_reports'))
    )
    op.create_index(op.f('ix_listing_reports_listing_id'), 'listing_reports', ['listing_id'], unique=False)
    op.create_index('ix_listing_reports_status_created', 'listing_reports', ['status', 'created_at'], unique=False)
    op.create_index('uq_listing_reports_open', 'listing_reports', ['listing_id', 'reporter_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.add_column('listings', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('moderation_reason', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'moderation_reason')
    op.drop_column('listings', 'moderated_at')
    op.drop_index('uq_listing_reports_open', table_name='listing_reports', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_listing_reports_status_created', table_name='listing_reports')
    op.drop_index(op.f('ix_listing_reports_listing_id'), table_name='listing_reports')
    op.drop_table('listing_reports')
    op.drop_index(op.f('ix_admin_actions_target_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    # ### end Alembic commands ###
